name: Build Electron App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build EXE com Electron Builder
        run: npm run dist -- --win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artefato Windows
        uses: actions/upload-artifact@v4
        with:
          name: sorteador-windows
          path: dist/*.exe